### ISSUE TITLE
[Deployment] Spring Boot , DB 배포 및 환경 설정

### ISSUE THREAD

**Issue by hoonii2** [7-lin/Final_Project_BE#2]
## Description(설명)
- CI/CD 구성
- 배포 구성

## Tasks(New feature)
- [x] Github action ci/cd
- [x] build file push to s3
- [x] nginx load balacing & 무중단 배포
- [x] ssl configuration

## References
[갓구글](https://www.google.co.kr)
