### ISSUE TITLE
[fix] jwt 토큰 발급을 위한 redis설정과 토큰검증, 관련된 예외처리, 로그인 기능 생성코드 수정

### ISSUE THREAD

**Issue by Chaseungjun** [7-lin/Final_Project_BE#33]
## Description(설명)
JWT 코드를 전체적으로 수정했다. 토큰을 redis에 저장하는데에 문제가 있어 추후에 다시 수정할 가능성이 높다 

## Tasks(New feature)
- [x] JWT 코드 수정
- [x] 관련된 예외처리 수정 및 추가
- [x] 회원 가입, 탈퇴, 정보 수정에 관한 코드 추가, 수정
