### ISSUE TITLE
[Config] Default spring boot 설정

### ISSUE THREAD

**Issue by hoonii2** [7-lin/Final_Project_BE#4]
## Description(설명)

- Spring Boot Project 를 위한 기본적인 설정

## Tasks(New feature)
- [x] Spring boot 프로젝트 설정
- [x] Domain Driven 패키지 구조 생성
- [ ] JPA Entity 생성
