### ISSUE TITLE
feat: 취소된 예약을 다시 되돌리는 기능을 구현한다.

### ISSUE THREAD

**Issue by ChoiByungok** [7-lin/Final_Project_BE#50]
## Tasks(New feature)
- [x] 취소된 예약을 가져와서 엔티티의 값을 WAITING로 바꾸는 로직을 구현한다.
- [x] 이미 취소된 예약이라면 취소할수 없다는 response를 내보낸다.
- [x] 예약 상세 페이지에 인원수 정보도 나올 수 있도록 수정한다.

## References
[link text](link addr)
